### ISSUE TITLE
Create the Stream selector pane

### ISSUE THREAD

**Issue by DanielHabenicht** [AWTPJ2021/dash-reference-ui#7]
Create the stream selector pane, similar to:
![image](https://user-images.githubusercontent.com/13590797/99987797-28afc000-2db1-11eb-94f6-0c5844c7dc9e.png)

- select different streams 
- Stop and Reload (maybe also auto reload)

PS: Should this be part of the settings pane?

**Comment by hieu2010** [comment]
change stream & auto load active --> load video
renaming: load --> [re]load
